### ISSUE TITLE
AttributeError: 'odict_keys' object has no attribute 'index'

### ISSUE THREAD

**Issue by Infernion** [ssrikanta/pytest-excel#13]
When try to make report get this error:
```
% py.test distributionhelper  --excelreport=report.xls --collect-only 
================================================================ test session starts =================================================================
platform linux -- Python 3.6.0, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /home/infernion/Projects/distribution_helper, inifile: setup.cfg
plugins: splinter-1.8.1, factoryboy-1.3.0, excel-1.2.0
collected 11 items 
<Module 'distributionhelper/tests/domain/test_account.py'>
  <Function 'test_account_init'>
<Module 'distributionhelper/tests/domain/test_campaign.py'>
  <Function 'test_campaign_init'>
<Module 'distributionhelper/tests/domain/test_message.py'>
  <Function 'test_atachement_init'>
  <Function 'test_message_init'>
  <Function 'test_tag_init'>
<Module 'distributionhelper/tests/domain/test_recipient.py'>
  <Function 'test_recipient_init'>
<Module 'distributionhelper/tests/domain/test_social_network.py'>
  <Function 'test_social_network_init'>
  <Function 'test_social_network_access_init'>
<Module 'distributionhelper/tests/domain/test_user.py'>
  <Function 'test_user_init'>
<Module 'distributionhelper/tests/domain/test_worker.py'>
  <Function 'test_worker_init'>
<Module 'distributionhelper/tests/web/test_login.py'>
  <Function 'test_login'>
Traceback (most recent call last):
  File "/home/infernion/.pyenv/versions/distribution_helper/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/config.py", line 57, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/main.py", line 127, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/main.py", line 122, in wrap_session
    exitstatus=session.exitstatus)
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/terminal.py", line 358, in pytest_sessionfinish
    outcome.get_result()
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/pytest_excel/pytest_excel.py", line 217, in pytest_sessionfinish
    self.create_sheet(fieldnames)
  File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/pytest_excel/pytest_excel.py", line 69, in create_sheet
    index_value = column_heading.index(heading) + 1
AttributeError: 'odict_keys' object has no attribute 'index'
```

**Comment by ssrikanta** [comment]
@Infernion Can you please provide your sample test file format

**Comment by mbhagavathula** [comment]
Tried with the same test program  but still getting the same error as quoted by @Infernion 

import pytest


class Test_Excel_Report(object):
  
    
  def test_excel_report_01(self):
    """
    Scenario: test_excel_report_01
    """
    assert True
    
  
  @pytest.mark.xfail(reason="passed Simply")  
  def test_excel_report_02(self):
    """
    Scenario: test_excel_report_02
    """
    assert True


  @pytest.mark.skip(reason="Skip for No Reason")
  def test_excel_report_03(self):
    """
    Scenario: test_excel_report_01
    """
    assert True


  @pytest.mark.xfail(reason="Failed Simply")
  def test_excel_report_04(self):
    """
    Scenario: test_excel_report_05
    """
    assert False


  def test_excel_report_05(self):
    """
    Scenario: test_excel_report_06
    """
    assert True is False

**Comment by ssrikanta** [comment]
This is an issue specific to python3, fix is on the way

**Comment by ssrikanta** [comment]
@Infernion @mbhagavathula Thank you very much for pointing out the issue. latest changes have the fixes for same.

**Comment by Infernion** [comment]
@ssrikanta wow, thank you for quikfix!

**Comment by Infernion** [comment]
Hmm, now another error appears :)

Whithout pytest-excel
```
% py.test --ini=distributionhelper/conf/test.ini -x --splinter-webdriver=chrome  
================================================================ test session starts =================================================================
platform linux -- Python 3.6.0, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /home/infernion/Projects/distribution_helper, inifile: setup.cfg
plugins: splinter-1.8.1, html-1.13.0, factoryboy-1.3.0, excel-1.2.1
collected 11 items 

distributionhelper/tests/test_domain.py ..........
distributionhelper/tests/web/test_login.py .

============================================================= 11 passed in 5.80 seconds ==============================================================
py.test --ini=distributionhelper/conf/test.ini -x --splinter-webdriver=chrome  4.74s user 0.46s system 65% cpu 7.953 total
```

And with

```
% py.test --ini=distributionhelper/conf/test.ini -x --splinter-webdriver=chrome --excelreport=report.xls
================================================================ test session starts =================================================================
platform linux -- Python 3.6.0, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /home/infernion/Projects/distribution_helper, inifile: setup.cfg
plugins: splinter-1.8.1, html-1.13.0, factoryboy-1.3.0, excel-1.2.1
collected 11 items 

distributionhelper/tests/test_domain.py 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/main.py", line 98, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/main.py", line 133, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/main.py", line 154, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/runner.py", line 66, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/runner.py", line 73, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/runner.py", line 135, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
INTERNALERROR>     wrap_controller.send(call_outcome)
INTERNALERROR>   File "/home/infernion/.pyenv/versions/distribution_helper/lib/python3.6/site-packages/pytest_excel/pytest_excel.py", line 190, in pytest_runtest_makereport
INTERNALERROR>     for k, v in item.keywords.iteritems():
INTERNALERROR> AttributeError: 'NodeKeywords' object has no attribute 'iteritems'
```

**Comment by mbhagavathula** [comment]
Thanks  

I am also observing similar error 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\main.py", line 98, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\main.py", line 133, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\main.py", line 154, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 613, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 254, in _wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 279, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 265, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\runner.py", line 66, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\runner.py", line 73, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\runner.py", line 135, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 613, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "c:\users\mbhagava\appdata\local\continuum\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 250, in _wrapped_call
INTERNALERROR>     wrap_controller.send(call_outcome)
INTERNALERROR>   File "C:\Users\mbhagava\Documents\PythonLib\pytest-excel-master\pytest-excel-master\pytest_excel\pytest_excel.py", line 190, in pytest_runtest_makereport
INTERNALERROR>     for k, v in item.keywords.iteritems():
INTERNALERROR> AttributeError: 'NodeKeywords' object has no attribute 'iteritems'

**Comment by ssrikanta** [comment]
@Infernion @mbhagavathula Guys sorry for that.
New fixes are in place. hope this works :smile:

**Comment by mbhagavathula** [comment]
Thanks @ssrikanta for the prompt fixes. I am able to generate excel report.
Can we add a column to this report with "Links"? In report html plugin we can see add extra information in the form of URL by adding a hook wrapper .

**Comment by ssrikanta** [comment]
yes.. of course we can. and will add soon,

**Comment by ssrikanta** [comment]
#14 Fixes this issue
