### ISSUE TITLE
MarkInfo is deprecated in pytest 4

### ISSUE THREAD

**Issue by pedmiston** [ssrikanta/pytest-excel#16]
I'm unable to run pytest-excel with pytest 4.1.0 due to a deprecation of MarkInfo. Here is the import that is failing for me:

`ImportError: cannot import name 'MarkInfo' from '_pytest.mark'`

Looking at the pytest docs, it seems there is a different way to get markers now:
https://github.com/pytest-dev/pytest/blob/38adb23bd245329d26b36fd85a43aa9b3dd0406c/doc/en/deprecations.rst#somefunctionmarkname

**Comment by ssrikanta** [comment]
This has been fixed sometime back
