### ISSUE TITLE
Add a Timestamp column

### ISSUE THREAD

**Issue by pxs8993** [ssrikanta/pytest-excel#20]
Hi,

Can you add a timestamp column in the excel report so that we can know when the test was actually run? and also, if we execute the test again, can you append the results in same excel file rather than removing the old results and updating with new one?

Regards,
Prasanna

**Comment by ssrikanta** [comment]
@pxs8993 , adding timestamp would be value added, changes are on the way.
For storing previous execution results, may not be possible here, I have another Django based web application for this

**Comment by ssrikanta** [comment]
#22 Fixes this
