### ISSUE TITLE
Add Marker information when using --collect-only

### ISSUE THREAD

**Issue by nitinthukral** [ssrikanta/pytest-excel#21]
`pytest --excelreport=report.xls --collect-only`
when only collecting the information from the pytest, it does not write the marker information in the excel compared to when the actual test is run.

**Comment by ssrikanta** [comment]
@nitinthukral , let me check that

**Comment by nitinthukral** [comment]
> @nitinthukral , let me check that

`def build_tests(self, item):

        result = OrderedDict()
        names = mangle_test_address(item.nodeid)

        result['suite_name'] = names[-2]
        result['test_name'] = names[-1]
        if item.obj.__doc__ is None:
          result['description'] = item.obj.__doc__
        else:
          result['description'] = item.obj.__doc__.strip()
        result['file_name'] = item.location[0]
        test_marker = []
        test_message = []
        for k, v in item.keywords.items():
            if isinstance(v, list):
                for x in v:
                    if isinstance(x, Mark):
                        if x.name != 'usefixtures':
                            test_marker.append(x.name)
                        if x.kwargs:
                            test_message.append(x.kwargs.get('reason'))

        test_markers = ', '.join(test_marker)
        result['markers'] = test_markers

        test_messages = ', '.join(test_message)
        result['message'] = test_messages
        self.append(result)
`

This is the modified build_tests() that worked for me. Let me know if you are fine with it. I could make a commit.

**Comment by ssrikanta** [comment]
@nitinthukral , Please commit and make a pull request, we will merge and publish

**Comment by ssrikanta** [comment]
@nitinthukral I have merged your code, and published

**Comment by nitinthukral** [comment]
@ssrikanta This totally went off my mind. I would have appreciated if you could have reminded once before merging.
