### ISSUE TITLE
Update the docstring in the methods for better readability

### ISSUE THREAD

**Issue by nitinthukral** [ssrikanta/pytest-excel#24]
#21 

- Add docstrings to the methods
- Remove any PEP8 errors or warnings
- Remove unused imports

**Comment by ssrikanta** [comment]
@nitinthukral  Can you provide more details

**Comment by nitinthukral89** [comment]
@ssrikanta It seems like I do not have the permission to create a New pull request on this repo. I also tried pushing my feature branch to this repo and gets permission denied error. Could you please grant the permission to this "nitinthukral89" username on your repo.

**Comment by ssrikanta** [comment]
@nitinthukral89 the above mentioned enhancements can be considered for any future releases, they don't have any impact bon the  functionality, please create an issue if any enhancements or issues with Library
Thanks for the support
