### ISSUE TITLE
Typo in Line 203

### ISSUE THREAD

**Issue by derlarsschneider** [ssrikanta/pytest-excel#38]
New in Version 1.5.1

pytest_excel/pytest_excel.py, line 203, in ExcelReporter
    @pytest.hookimpl(hookwraper=True)
TypeError: HookimplMarker.__call__() got an unexpected keyword argument 'hookwraper'

It should be hookwrapper instead, I think.

**Comment by ssrikanta** [comment]
Ops sorry fix in the way
